apiVersion: v1
kind: Pod
metadata:
  name: kubedoom-with-novnc
  labels:
    app: kubedoom
spec:
  serviceAccountName: kubedoom

  containers:
  # --- Kubedoom Container (VNC Server) ---
  - name: kubedoom
    image: ghcr.io/storax/kubedoom:latest
    imagePullPolicy: Always
    # UPDATED: Added "-file /doom-files/custom.wad" to load sprites
    args: 
      - "-file"
      - "/doom-files/custom.wad" # <--- Loads the custom WAD from the mounted path
      - "-mode"
      - "namespaces"
    ports:
    - containerPort: 5900
      name: vnc-port
    securityContext:
      runAsNonRoot: false
      runAsUser: 0
    volumeMounts: # <--- Maps the volume to a path inside the container
    - name: wad-volume
      mountPath: /doom-files 

  # --- noVNC Container (Web Proxy) ---
  - name: novnc-proxy
    image: theasp/novnc:latest
    imagePullPolicy: Always
    ports:
    - containerPort: 8080
      name: web-port
    env:
    - name: VNC_HOST
      value: "localhost"
    - name: VNC_PORT
      value: "5900"
    - name: PORT
      value: "8080"
  
  volumes: # <--- Defines the source of the data (your ConfigMap)
  - name: wad-volume
    configMap:
      name: kubedoom-sprites # <--- **ASSUMES** you have created this ConfigMap
