# This manifest defines the necessary Kubernetes resources to run Kubedoom
# in 'namespaces' mode, allowing the game to target and delete entire namespaces.

# -------------------------------------------------------------------
# 1. ServiceAccount for Kubedoom
# -------------------------------------------------------------------
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubedoom
  namespace: default
---
# -------------------------------------------------------------------
# 2. ClusterRole defining Kubedoom's permissions
#    UPDATED: Added 'delete' verb for 'namespaces'.
# -------------------------------------------------------------------
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubedoom
rules:
# Permissions for Kubedoom to find, delete, and manage pods and nodes
- apiGroups: [""]
  resources: ["pods", "pods/exec", "nodes"]
  verbs: ["get", "list", "watch", "delete"]
# Permissions for Kubedoom to target and delete namespaces
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "delete"] # <--- ADDED 'delete' verb
---
# -------------------------------------------------------------------
# 3. ClusterRoleBinding linking the ServiceAccount to the ClusterRole
# -------------------------------------------------------------------
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubedoom
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubedoom
subjects:
- kind: ServiceAccount
  name: kubedoom
  namespace: default
---
# -------------------------------------------------------------------
# 4. Multi-Container Deployment Definition (MODIFIED TO USE CUSTOM .WAD FILE)
# -------------------------------------------------------------------
apiVersion: apps/v1  # Deployment uses apps/v1
kind: Deployment     # Changed from Pod to Deployment
metadata:
  name: kubedoom-deployment # Renamed the resource for clarity
  labels:
    app: kubedoom
spec:
  # The Deployment must define the desired state
  replicas: 1
  selector:
    matchLabels:
      app: kubedoom
      
  # The old Pod metadata/spec is now nested under the 'template' key
  template:
    metadata:
      labels:
        app: kubedoom
    spec:
      serviceAccountName: kubedoom

      # --- INIT CONTAINER: Downloads the custom .wad file ---
      initContainers:
      - name: download-wad-file
        image: busybox:1.36 # A minimal image that includes 'wget'
        command: ["wget"]
        # Use the raw GitHub URL to download the custom .wad content.
        # It is saved to the shared 'wad-volume' under the required name 'doom2.wad'.
        args:
          - "-O"
          - "/wad-data/doom2.wad"
          - "https://raw.githubusercontent.com/ndouglas-cloudsmith/minecraft/main/doom2.wad"
        volumeMounts:
          - name: wad-volume
            mountPath: /wad-data # Mounts the emptyDir volume

      # --- Main Containers ---
      containers:
      # --- Kubedoom Container (VNC Server) ---
      - name: kubedoom
        image: docker.cloudsmith.io/acme-corporation/acme-repo-one/kubedoom:latest
        imagePullPolicy: Always
        args: ["-mode", "namespaces"]
        ports:
        - containerPort: 5900
          name: vnc-port
        securityContext:
          # RELAXED SECURITY CONTEXT
          runAsNonRoot: false
          runAsUser: 0
        # --- VOLUME MOUNT: Mounts the downloaded file, replacing the default ---
        volumeMounts:
          - name: wad-volume
            # This mounts the specific file from the volume...
            subPath: doom2.wad
            # ...directly over the default file path, replacing the original.
            mountPath: /doom2.wad 

      # --- noVNC Container (Web Proxy) ---
      - name: novnc-proxy
        image: docker.cloudsmith.io/acme-corporation/acme-repo-one/novnc:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: web-port
        env:
        - name: VNC_HOST
          value: "localhost"
        - name: VNC_PORT
          value: "5900"
        - name: PORT
          value: "8080"

      # --- VOLUME DEFINITION: The temporary volume shared between the Init and Main containers ---
      volumes:
        - name: wad-volume
          emptyDir: {} # Temporary volume tied to the Pod's lifecycle
